#!/usr/bin/env python3
"""Writes runbloom.app's copy of the mark from the same artwork the app uses.

    python3 Tools/icon/site.py [path to the runbloom checkout]

The site is a separate repository and this file does not commit anything there.
It writes the assets and prints what changed; the commit is a human decision
made in that repository.

WHY THIS EXISTS. The site's brand assets were exported by hand once, from
whatever the icon happened to be that afternoon, and the moment the icon moved
they were a picture of an older app. Every file below is derived, so the only
way for the site to be out of step now is for nobody to have run this.

WHAT THE SITE DRAWS AND WHAT IT DOES NOT.

  brand/mark.svg          design.render()'s full bleed composite, unchanged and
                          uncropped. The tile is the whole canvas in this
                          round, so the file carries no padding of its own. Its
                          contact shadows are baked in on purpose: the site
                          draws the mark flat with nothing under it to seat the
                          pieces
  brand/icon-512.png      the same file at 512, 400 and 200. The webps are
  brand/icon-400.webp     cwebp at quality 90, which is what the committed
  brand/icon-200.webp     files were made at
  brand/apple-touch-icon-180.png
                          the same drawing with the tile's own clip taken off,
                          so the Foam ground runs to the square's corners. iOS
                          masks the home screen icon to its own shape and a
                          second rounded cut inside it reads as a mistake
  brand/wordmark-dark.svg the mark set beside the type, at 240 in a 932 by 340
                          box. Only the mark is regenerated: the letterforms
                          are paths in that file and are left exactly as they
                          are

  favicon.svg             THE FRAME IS DELIBERATELY DROPPED HERE, and this
  brand/favicon-32.png    script does not touch these three. They carry
  favicon.ico             `gen10.unframed`, the figure with no margin and the
                          lanes opened up on its own dark tile, because at 16
                          pixels the margin is two pixels of white, the
                          crossing it exists for is gone, and a near white tile
                          on a light tab bar is barely there at all. That is
                          the same swap the app's `.icns` makes below 64. The
                          small artwork has not changed, and the script checks
                          that it has not rather than assuming it

  screenshots/og.png      NOT written here. The social card is an HTML page
                          that reads brand/mark.svg, so it has to be
                          re-rendered through headless Chrome after this runs.
                          public/screenshots/MANIFEST.md carries the command
"""
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import design  # noqa: E402
import gen10  # noqa: E402
import lib  # noqa: E402
import lib9  # noqa: E402

DEFAULT_SITE = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(HERE))),
                            "runbloom")

MARK_NOTE = """<!--
  The Bloom mark: the app's icon, `tongue` at a margin of 150 with the shine
  the owner chose. A near white Foam ground fills the tile, a Deep panel sits
  inset within it, two lanes arrive and a pale bar crosses. Every piece is
  graded across its own height, lighter at its own top and deeper at its own
  bottom, so no piece's average tone leaves the palette.

  The panel grows a spur along the bar's own path and runs out to the tile's
  edge, so what lies on the white margin is Deep with the pale bar inside it.
  Shallow against Foam measures 1.26 where two layers need 1.60, so without
  that spur the bar on the margin is invisible. Do not take it out. It is 17
  units proud of the bar above and below, which measures 11 canvas units on
  each side, and the two are concentric.

  Generated by Tools/icon/site.py in the app repository, from the same
  design.py the app icon is built from. The tile here is the whole canvas, so
  this file is already cropped tight and carries no padding. Its contact
  shadows are baked in on purpose: the site draws the mark flat, with nothing
  underneath it to seat the pieces. Do not strip them, and do not adjust the
  geometry or the colours by hand.

  Below about 32 pixels the frame costs more than it gives, so use the
  unframed opened-up artwork instead, which is what ../favicon.svg and
  favicon-32.png carry.
-->
"""


def flush(body):
    """The composite with no tile clip, so the ground runs to the corners."""
    return lib9.HEAD + "<defs>" + lib.defs() + "</defs>" + body + "</svg>"


def rsvg(src, size, out):
    subprocess.run(["rsvg-convert", "-w", str(size), "-h", str(size), src, "-o", out],
                   check=True)


def webp(src, out, quality=90):
    subprocess.run(["cwebp", "-quiet", "-q", str(quality), src, "-o", out], check=True)


def splice_wordmark(path, marksvg):
    """The mark swapped into the wordmark, ids prefixed so they cannot collide
    with the type's.

    Everything outside the two spliced regions is kept byte for byte, including
    the letterform paths and the note above the mark, because this script has
    no opinion about the type.
    """
    w = open(path).read()
    i, j = w.index("<defs>"), w.index("</defs>")
    rest = w[j + 7:]
    k = rest.index('<svg x=')
    end = rest.index("</svg>", k)

    a, b = marksvg.index("<defs>"), marksvg.index("</defs>")
    mdefs = marksvg[a + 6:b]
    mbody = marksvg[b + 7:marksvg.rindex("</svg>")]

    ids = set(re.findall(r'id="([^"]+)"', mdefs))

    def prefixed(s):
        # Longest first, so `c1` cannot eat the front of `c14`.
        for n in sorted(ids, key=len, reverse=True):
            s = s.replace('id="%s"' % n, 'id="mark-%s"' % n)
            s = s.replace("url(#%s)" % n, "url(#mark-%s)" % n)
        return s

    nested = ('<svg x="48" y="50" width="240" height="240" viewBox="0 0 1024 1024">'
              + prefixed(mbody) + "</svg>")
    return w[:i + 6] + prefixed(mdefs) + w[j:j + 7] + rest[:k] + nested + rest[end + 6:]


def main(site=None):
    site = site or DEFAULT_SITE
    brand = os.path.join(site, "public", "brand")
    if not os.path.isdir(brand):
        raise SystemExit("site.py: no public/brand in " + site)

    before = {}
    for name in sorted(os.listdir(brand)) + ["../favicon.svg", "../favicon.ico"]:
        p = os.path.join(brand, name)
        if os.path.isfile(p):
            before[os.path.normpath(p)] = open(p, "rb").read()

    _, full, _ = design.render()
    # A second pass for the flush cut, because `flush` reads lib's def table and
    # design.render leaves it holding the flat body's.
    lib.SMALL = False
    lib.reset()
    body = design.body()
    flushed = flush(body)

    mark = os.path.join(brand, "mark.svg")
    with open(mark, "w") as f:
        f.write(MARK_NOTE + full)

    rsvg(mark, 512, os.path.join(brand, "icon-512.png"))
    for size in (400, 200):
        tmp = os.path.join(HERE, ".build", "site-%d.png" % size)
        os.makedirs(os.path.dirname(tmp), exist_ok=True)
        rsvg(mark, size, tmp)
        webp(tmp, os.path.join(brand, "icon-%d.webp" % size))

    tmp = os.path.join(HERE, ".build", "site-flush.svg")
    with open(tmp, "w") as f:
        f.write(flushed)
    rsvg(tmp, 180, os.path.join(brand, "apple-touch-icon-180.png"))

    wordmark = os.path.join(brand, "wordmark-dark.svg")
    if os.path.isfile(wordmark):
        # Read all the way through BEFORE opening for writing: opening in "w"
        # truncates, and a splice that reads the file it is about to replace
        # gets an empty string if the two happen in one statement.
        spliced = splice_wordmark(wordmark, full)
        with open(wordmark, "w") as f:
            f.write(spliced)

    # The three the frame is dropped for. Checked, not written: if the small
    # artwork ever moves, this says so instead of leaving the tab icon stale.
    small, _ = gen10.unframed(small=True)
    fav = os.path.join(site, "public", "favicon.svg")
    carried = open(fav).read()
    stale = carried[carried.index("<svg"):].strip() != small.strip()
    print("favicon.svg: " + ("STALE, the unframed artwork has moved and the tab "
                             "icon, favicon-32.png and favicon.ico all need "
                             "rebuilding" if stale else
                             "still the current unframed artwork, left alone"))

    for p, was in sorted(before.items()):
        if not os.path.isfile(p):
            continue
        now = open(p, "rb").read()
        if now != was:
            print("changed: " + os.path.relpath(p, site))
    print("re-render public/screenshots/og.png: it embeds brand/mark.svg. "
          "The command is in public/screenshots/MANIFEST.md")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else None)
