import Foundation
import BloomClient

/// Which ignored paths are worth naming when a worktree is about to be deleted.
///
/// The check they feed exists for a real reason: `git status --porcelain` does not list ignored
/// files and `git worktree remove` deletes them without a word. Bloom copies `.env*` into every
/// worktree, which makes an edited `.env` both the likeliest file to be destroyed and the one
/// nobody thinks to check.
///
/// Naming every divergent ignored file turned that into a confirmation listing 981 paths, nearly
/// all of them `node_modules/...`. A list nobody can read is not a safety check; it buries the
/// one line that mattered under the noise.
///
/// The rule that separates the two is reproducibility. `node_modules` is ignored precisely
/// because a package manager rebuilds it from a lockfile that IS in git, so losing it costs an
/// install rather than a piece of work. Nothing rebuilds `.env`. A path is therefore left out
/// when it lies inside a directory whose entire job is to hold something a tool regenerates, and
/// named otherwise.
///
/// Two things worth being explicit about:
///
/// - This is a list of names, not a clever test. Nothing can ask the filesystem whether a file
///   could be rebuilt, so the honest implementation is a curated set with a bias: a name goes in
///   only when a hand-written file living under it would be surprising. Names that are sometimes
///   build output and sometimes not (`out`, `tmp`, `data`, `.idea`) are deliberately absent,
///   because leaving one out costs a line of noise and putting one in costs somebody their work.
/// - `.bloom` is ours. The app creates it to hold prompt attachments, so listing it as work at
///   risk is Bloom warning the user about Bloom.
public enum ReproduciblePaths {
    /// Directory names a package manager, build tool or cache owns end to end.
    ///
    /// Matched against every component of the path, because a monorepo's `apps/web/node_modules`
    /// is as reproducible as a root one.
    public static let directories: Set<String> = [
        // Ours, so never the user's work to lose.
        ".bloom",
        // Dependency installs, each rebuilt from a lockfile or manifest that is in git.
        "node_modules", "bower_components", "jspm_packages", ".pnpm", ".pnpm-store", ".yarn",
        "vendor", "Pods", "Carthage", ".venv", "venv", "virtualenv", ".tox", ".bundle",
        ".cargo", ".gradle", ".m2", ".stack-work", ".pub-cache", ".dart_tool", "_build",
        // Build output.
        "dist", "build", ".build", "target", ".next", ".nuxt", ".output", ".svelte-kit",
        ".astro", ".docusaurus", ".vercel", ".netlify", "DerivedData", ".swiftpm",
        // Caches and coverage.
        ".cache", ".turbo", ".parcel-cache", ".vite", "__pycache__", ".pytest_cache",
        ".mypy_cache", ".ruff_cache", ".phpunit.cache", ".sass-cache", ".nyc_output",
        ".terraform", ".serverless", "coverage",
    ]

    /// Whole file names nobody writes by hand.
    public static let files: Set<String> = [
        ".DS_Store", "Thumbs.db", ".eslintcache", ".phpunit.result.cache",
    ]

    /// Suffixes of compiled artefacts, regenerated by whatever reads them.
    public static let suffixes = [".pyc", ".pyo", ".class"]

    /// Whether losing this path costs an install rather than a piece of work.
    ///
    /// - Parameter path: repository-relative, as git prints it. A trailing slash means git
    ///   collapsed a wholly ignored directory into one entry, which is the case this exists for.
    public static func canBeRebuilt(_ path: String) -> Bool {
        let components = path.split(separator: "/", omittingEmptySubsequences: true)
        guard let last = components.last.map(String.init) else { return false }

        if components.contains(where: { directories.contains(String($0)) }) { return true }
        if files.contains(last) { return true }
        return suffixes.contains { last.hasSuffix($0) }
    }
}

public typealias WorkspaceSafetyReport = BloomClient.WorkspaceSafetyReport

/// Everything throwing a workspace away would destroy, gathered before anything is thrown.
///
/// This is the expensive half of `Git`: it walks every ref in the repository and byte-compares
/// the ignored files a worktree is carrying, which is why nothing polls it and why the cheap
/// question a pull request strip asks is `LocalWork` in `Git+Diffs.swift` instead. It is all
/// computed up front because removing a worktree and deleting its branch leaves nothing to
/// recover from afterwards.
extension Git {
    /// Everything archiving this workspace would destroy, gathered before anything is removed.
    ///
    /// `unpushedCommits` deliberately means "reachable from this branch and from no other ref",
    /// not "ahead of the base branch". A commit that also lives on a remote, on a tag or on
    /// another branch survives deleting this one, and refusing to archive over it would be
    /// noise. A commit nothing else points at does not survive.
    public static func safetyReport(
        worktree: String,
        branch: String,
        base: String,
        repo: String
    ) async throws -> WorkspaceSafetyReport {
        try validate(branch: branch)

        var report = WorkspaceSafetyReport()

        // A directory that is not there holds nothing, so an empty report is the true answer. A
        // directory that IS there and cannot be read as a repository is a different thing
        // entirely: git could not be asked, and every field below would be a zero standing in for
        // an answer nobody has. `isSafeToDiscard` would read that as "nothing at stake" and let
        // the worktree be deleted, so it throws instead, and the caller shows the reason.
        var isDetached = false
        if FileManager.default.fileExists(atPath: worktree) {
            guard await isRepository(worktree) else {
                throw ShellError(
                    command: "git status",
                    status: 128,
                    stderr: "\(worktree) is not a git worktree, so what is in it cannot be checked"
                )
            }
            let status = try await checkRaw(["status", "--porcelain", "-z"], in: worktree)
            (report.hasUncommittedChanges, report.untrackedFiles) = parseStatus(status.stdout)
            report.modifiedIgnoredFiles = try await divergentIgnoredFiles(worktree: worktree, repo: repo)
            isDetached = try await isDetachedHead(worktree: worktree)
        }

        let branchIsThere = await branchExists(branch, in: repo)
        guard isDetached || branchIsThere else { return report }

        // One ref walk for both counts. A detached worktree used to walk every head, remote and
        // tag here and again inside `detachedCommitCount`, which on a repository with thousands
        // of tags is the expensive call in this whole report.
        let refs = try await allRefs(in: repo)

        if isDetached {
            report.detachedCommits = try await detachedCommitCount(worktree: worktree, excluding: refs)
        }
        guard branchIsThere else { return report }

        // Feeding the other refs in on stdin rather than as arguments, because a repository with
        // thousands of tags would otherwise blow past the argument limit.
        let negated = refs
            .filter { $0 != "refs/heads/\(branch)" }
            .map { "^\($0)" }
            .joined(separator: "\n")
        let unique = try await check(
            ["rev-list", "--count", "--stdin", "refs/heads/\(branch)"],
            in: repo,
            stdin: negated.isEmpty ? "\n" : negated + "\n"
        )
        report.unpushedCommits = Int(unique.trimmed) ?? 0

        if (try? validate(ref: base, label: "base branch")) != nil {
            let merged = try await run(
                ["merge-base", "--is-ancestor", "refs/heads/\(branch)", base], in: repo
            )
            report.isBranchMerged = merged.ok
        }

        return report
    }

    /// `status --porcelain -z` records: `XY path`, and for a rename or copy the new path is
    /// followed by a second record holding the old path.
    static func parseStatus(_ data: Data) -> (dirty: Bool, untracked: [String]) {
        var dirty = false
        var untracked: [String] = []
        var records = nulRecords(data)[...]

        while let record = records.popFirst() {
            guard record.count > 3 else { continue }
            let code = String(decoding: record.prefix(2), as: UTF8.self)
            let path = String(decoding: record.dropFirst(3), as: UTF8.self)
            if code == "??" {
                untracked.append(path)
            } else {
                dirty = true
                if code.contains("R") || code.contains("C") { _ = records.popFirst() }
            }
        }
        return (dirty, untracked)
    }

    /// Ignored paths in the worktree that the main checkout does not have, or has differently,
    /// with everything a tool can rebuild left out. See `ReproduciblePaths`.
    ///
    /// Only ignored paths are considered, because tracked and untracked ones are already covered.
    /// An ignored file that matches the main checkout byte for byte is not a loss: Bloom copied it
    /// there and the original is still where it came from.
    ///
    /// `--directory` is what makes this cheap enough to run in front of a confirmation. It
    /// collapses a wholly ignored directory into one record with a trailing slash, so a
    /// `node_modules` of forty thousand files costs a single line instead of forty thousand
    /// paths and forty thousand file reads. It is also the level the reproducibility rule wants
    /// to work at: the answer for `node_modules/` is the answer for everything inside it.
    static func divergentIgnoredFiles(worktree: String, repo: String) async throws -> [String] {
        let ignored = try await checkRaw(
            ["ls-files", "--others", "--ignored", "--exclude-standard", "--directory", "-z"],
            in: worktree
        )

        var paths: [String] = []
        for record in nulRecords(ignored.stdout) {
            let path = String(decoding: record, as: UTF8.self)
            guard !path.isEmpty, !ReproduciblePaths.canBeRebuilt(path) else { continue }
            paths.append(path)
        }

        // Git lists a directory and, sometimes, a directory nested inside it. Reporting both
        // would name the same loss twice, so only the outermost entry survives: it covers
        // everything the inner one did.
        let directories = paths.filter { $0.hasSuffix("/") }
        let covering = paths.filter { path in
            !directories.contains { $0 != path && path.hasPrefix($0) }
        }

        var divergent: [String] = []
        for path in covering {
            let here = (worktree as NSString).appendingPathComponent(path)
            let there = (repo as NSString).appendingPathComponent(path)
            if path.hasSuffix("/") {
                // Named as one line rather than expanded. "storage/logs/" says what would be
                // lost; its two hundred files say it two hundred times.
                if directoryDiffers(here, there) { divergent.append(path) }
            } else if fileDiffers(here, there) {
                divergent.append(path)
            }
        }
        return divergent.sorted()
    }

    /// Whether two files at the same repository-relative path hold different bytes.
    ///
    /// Size first. Two files of different lengths cannot be equal, and answering from the inode
    /// rather than from the contents is what keeps a directory of large ignored files off the
    /// critical path of a confirmation.
    ///
    /// Every uncertain answer is "differs". A file that exists here and cannot be read is not
    /// evidence that nothing is at stake; it is the absence of evidence, and the version of this
    /// that skipped an unreadable file quietly counted it as safe to destroy. The only case that
    /// returns false without looking is a file that is no longer there at all, which cannot be
    /// destroyed by removing the directory it has already left.
    static func fileDiffers(_ here: String, _ there: String) -> Bool {
        let manager = FileManager.default
        guard manager.fileExists(atPath: here) else { return false }
        // Exists only in the worktree, so removing the worktree is the end of it.
        guard manager.fileExists(atPath: there) else { return true }

        let mySize = (try? manager.attributesOfItem(atPath: here)[.size] as? Int)
        let theirSize = (try? manager.attributesOfItem(atPath: there)[.size] as? Int)
        if let mySize, let theirSize, mySize != theirSize { return true }

        guard let mine = manager.contents(atPath: here) else { return true }
        guard let theirs = manager.contents(atPath: there) else { return true }
        return mine != theirs
    }

    /// Whether a wholly ignored directory holds anything the main checkout does not.
    ///
    /// Bounded on purpose. An unknown ignored directory big enough to make this expensive is
    /// already something whose contents nobody is going to read out of a confirmation, and a
    /// walk that could run for a minute is exactly what this rewrite exists to remove. Past the
    /// bound the answer is "it differs", because the alternative is telling somebody there is
    /// nothing at stake on the strength of a check that gave up.
    static func directoryDiffers(_ here: String, _ there: String, limit: Int = 2_000) -> Bool {
        let manager = FileManager.default
        guard manager.fileExists(atPath: here) else { return false }
        guard manager.fileExists(atPath: there) else { return true }

        guard let walk = manager.enumerator(atPath: here) else { return true }
        var seen = 0
        for case let relative as String in walk {
            var isDirectory: ObjCBool = false
            let file = (here as NSString).appendingPathComponent(relative)
            guard manager.fileExists(atPath: file, isDirectory: &isDirectory), !isDirectory.boolValue
            else { continue }

            seen += 1
            if seen > limit { return true }
            if fileDiffers(file, (there as NSString).appendingPathComponent(relative)) { return true }
        }
        return false
    }

    /// Whether HEAD here is a commit rather than a branch, which is what an agent running
    /// `git checkout` in its worktree leaves behind.
    static func isDetachedHead(worktree: String) async throws -> Bool {
        let head = try await run(["symbolic-ref", "--quiet", "HEAD"], in: worktree)
        return !head.ok
    }

    /// Every ref in the repository, which is the walk `safetyReport` pays for once and hands to
    /// both counts below.
    static func allRefs(in repo: String) async throws -> [String] {
        try await check(
            ["for-each-ref", "--format=%(refname)", "refs/heads", "refs/remotes", "refs/tags"],
            in: repo
        ).lines
    }

    /// Commits reachable from the worktree's own detached HEAD and from no ref anywhere. Those
    /// commits are held only by the per-worktree reflog, which `git worktree remove` deletes.
    ///
    /// Only ever asked of a detached HEAD: on a branch the answer is zero by construction.
    static func detachedCommitCount(worktree: String, excluding refs: [String]) async throws -> Int {
        let negated = refs.map { "^\($0)" }.joined(separator: "\n")
        let unique = try await run(
            ["rev-list", "--count", "--stdin", "HEAD"],
            in: worktree,
            stdin: negated.isEmpty ? "\n" : negated + "\n"
        )
        guard unique.ok else { return 0 }
        return Int(unique.trimmed) ?? 0
    }
}
