import Foundation

/// Which ignored paths are worth naming when a worktree is about to be deleted.
///
/// The check they feed exists for a real reason: `git status --porcelain` does not list ignored
/// files and `git worktree remove` deletes them without a word. Bloom copies `.env*` into every
/// worktree, which makes an edited `.env` both the likeliest file to be destroyed and the one
/// nobody thinks to check.
///
/// Naming every divergent ignored file turned that into a confirmation listing 981 paths, nearly
/// all of them `node_modules/...`. A list nobody can read is not a safety check; it buries the
/// one line that mattered under the noise.
///
/// The rule that separates the two is reproducibility. `node_modules` is ignored precisely
/// because a package manager rebuilds it from a lockfile that IS in git, so losing it costs an
/// install rather than a piece of work. Nothing rebuilds `.env`. A path is therefore left out
/// when it lies inside a directory whose entire job is to hold something a tool regenerates, and
/// named otherwise.
///
/// Two things worth being explicit about:
///
/// - This is a list of names, not a clever test. Nothing can ask the filesystem whether a file
///   could be rebuilt, so the honest implementation is a curated set with a bias: a name goes in
///   only when a hand-written file living under it would be surprising. Names that are sometimes
///   build output and sometimes not (`out`, `tmp`, `data`, `.idea`) are deliberately absent,
///   because leaving one out costs a line of noise and putting one in costs somebody their work.
/// - `.bloom` is ours. The app creates it to hold prompt attachments, so listing it as work at
///   risk is Bloom warning the user about Bloom.
public enum ReproduciblePaths {
    /// Directory names a package manager, build tool or cache owns end to end.
    ///
    /// Matched against every component of the path, because a monorepo's `apps/web/node_modules`
    /// is as reproducible as a root one.
    public static let directories: Set<String> = [
        // Ours, so never the user's work to lose.
        ".bloom",
        // Dependency installs, each rebuilt from a lockfile or manifest that is in git.
        "node_modules", "bower_components", "jspm_packages", ".pnpm", ".pnpm-store", ".yarn",
        "vendor", "Pods", "Carthage", ".venv", "venv", "virtualenv", ".tox", ".bundle",
        ".cargo", ".gradle", ".m2", ".stack-work", ".pub-cache", ".dart_tool", "_build",
        // Build output.
        "dist", "build", ".build", "target", ".next", ".nuxt", ".output", ".svelte-kit",
        ".astro", ".docusaurus", ".vercel", ".netlify", "DerivedData", ".swiftpm",
        // Caches and coverage.
        ".cache", ".turbo", ".parcel-cache", ".vite", "__pycache__", ".pytest_cache",
        ".mypy_cache", ".ruff_cache", ".phpunit.cache", ".sass-cache", ".nyc_output",
        ".terraform", ".serverless", "coverage",
    ]

    /// Whole file names nobody writes by hand.
    public static let files: Set<String> = [
        ".DS_Store", "Thumbs.db", ".eslintcache", ".phpunit.result.cache",
    ]

    /// Suffixes of compiled artefacts, regenerated by whatever reads them.
    public static let suffixes = [".pyc", ".pyo", ".class"]

    /// Whether losing this path costs an install rather than a piece of work.
    ///
    /// - Parameter path: repository-relative, as git prints it. A trailing slash means git
    ///   collapsed a wholly ignored directory into one entry, which is the case this exists for.
    public static func canBeRebuilt(_ path: String) -> Bool {
        let components = path.split(separator: "/", omittingEmptySubsequences: true)
        guard let last = components.last.map(String.init) else { return false }

        if components.contains(where: { directories.contains(String($0)) }) { return true }
        if files.contains(last) { return true }
        return suffixes.contains { last.hasSuffix($0) }
    }
}

/// What throwing a workspace away would destroy.
///
/// Removing a worktree and deleting its branch leaves nothing to recover from: the files are
/// gone from disk and, once no ref points at them, the commits are unreachable and eventually
/// pruned. So every field here is computed and shown before anything is deleted.
public struct WorkspaceSafetyReport: Sendable, Hashable {
    /// Tracked files with modifications that were never committed.
    public var hasUncommittedChanges: Bool
    /// Files git has never seen. These are the easiest to lose and the hardest to notice.
    public var untrackedFiles: [String]
    /// Commits reachable from this branch and from no other ref in the repository. Nothing
    /// else, local or remote, is holding on to them.
    public var unpushedCommits: Int
    /// Whether the base branch already contains this branch's history.
    public var isBranchMerged: Bool
    /// Ignored paths that differ from the main checkout, or exist only here, minus everything a
    /// tool can rebuild. A trailing slash means a whole directory, named once.
    ///
    /// `git status --porcelain` does not list ignored files and `git worktree remove` deletes them
    /// without a word, so these were invisible. Bloom copies `.env*` into every worktree, which
    /// makes an edited `.env` both the likeliest file to be destroyed and the one nobody would
    /// think to check. What is NOT here, and why, is `ReproduciblePaths`.
    public var modifiedIgnoredFiles: [String]
    /// Commits held only by this worktree's own HEAD, on no branch at all.
    ///
    /// An agent that runs `git checkout` leaves HEAD detached. Commits made after that belong to
    /// no ref, so counting commits on the branch misses them entirely, and removing the worktree
    /// throws away the per-worktree reflog that was the last thing holding them.
    public var detachedCommits: Int

    public init(
        hasUncommittedChanges: Bool = false,
        untrackedFiles: [String] = [],
        unpushedCommits: Int = 0,
        isBranchMerged: Bool = false,
        modifiedIgnoredFiles: [String] = [],
        detachedCommits: Int = 0
    ) {
        self.hasUncommittedChanges = hasUncommittedChanges
        self.untrackedFiles = untrackedFiles
        self.unpushedCommits = unpushedCommits
        self.isBranchMerged = isBranchMerged
        self.modifiedIgnoredFiles = modifiedIgnoredFiles
        self.detachedCommits = detachedCommits
    }

    /// A merged branch's commits live on in the base branch, so they are not counted as a loss.
    ///
    /// The cautious form of the question: it assumes the branch is being deleted along with the
    /// worktree, and it knows only what git knows. Callers with better information should ask
    /// `isSafeToDiscard(deletingBranch:isPullRequestMerged:)` instead.
    public var isSafeToDiscard: Bool {
        isSafeToDiscard(deletingBranch: true)
    }

    /// Whether archiving destroys anything, given the two things a git process cannot see.
    ///
    /// - Parameter deletingBranch: whether the branch goes with the worktree. Committed work is
    ///   only ever at risk when it does. A worktree is a checkout: remove it while the branch
    ///   survives and every commit is still on the branch, which is the same reasoning
    ///   `isRestorableFromBranch` is built on and the reason that archive can be undone.
    /// - Parameter isPullRequestMerged: GitHub says the pull request for this branch was merged.
    ///   Only ever passed `true` when GitHub actually said so, never inferred from its silence,
    ///   because being wrong here is only dangerous in one direction. It matters because
    ///   `isBranchMerged` is git's reachability test, and a squash merge rewrites the branch's
    ///   commits onto the base rather than joining its history to it. Git's answer for a squash
    ///   merged branch is "not merged" while every line of its work is already on main, and that
    ///   is the single most common way this check is wrong.
    public func isSafeToDiscard(deletingBranch: Bool, isPullRequestMerged: Bool = false) -> Bool {
        // Everything git was keeping no copy of. It lives in the worktree directory and nowhere
        // else, so it goes whether the branch survives or not.
        let workingCopyIsClean = !hasUncommittedChanges
            && untrackedFiles.isEmpty
            && modifiedIgnoredFiles.isEmpty
            && detachedCommits == 0

        guard workingCopyIsClean else { return false }
        guard deletingBranch else { return true }
        return unpushedCommits == 0 || isBranchMerged || isPullRequestMerged
    }

    /// One line per thing that would be destroyed, for an error message or a confirmation sheet.
    public var losses: [String] {
        losses(deletingBranch: true)
    }

    /// The same list, narrowed to what is actually at stake for this particular archive.
    ///
    /// A confirmation that lists commits as a loss when the branch is being kept is a
    /// confirmation nobody will read twice. See `isSafeToDiscard(deletingBranch:)` for both
    /// arguments.
    ///
    /// Everything, in one voice, which is right for `WorkspaceError.unsafeToArchive` and wrong
    /// for the confirmation. The confirmation asks for the two halves separately. See
    /// `irreversibleLosses(deletingBranch:isPullRequestMerged:)`.
    public func losses(deletingBranch: Bool, isPullRequestMerged: Bool = false) -> [String] {
        irreversibleLosses(deletingBranch: deletingBranch, isPullRequestMerged: isPullRequestMerged)
            + ignoredFileNotes
    }

    /// The half of the list that is genuinely gone for good: work git was keeping no other copy
    /// of, and commits nothing else points at.
    ///
    /// Split out from `ignoredFileNotes` because saying both in one red sentence is how a
    /// destructive button stops being read. The owner merged a pull request, pressed Archive, and
    /// was offered "Archive and lose that work" over thirteen ignored paths: a `.env`, generated
    /// route and type files, an attachments folder. None of that was ever in a commit, none of it
    /// was meant to be, and the code itself was already on the default branch. Spending the
    /// strongest words in the app on that teaches people to click through them, which is the last
    /// thing wanted on the one action that cannot be undone.
    public func irreversibleLosses(
        deletingBranch: Bool, isPullRequestMerged: Bool = false
    ) -> [String] {
        var losses: [String] = []
        if hasUncommittedChanges {
            losses.append("uncommitted changes to tracked files")
        }
        if !untrackedFiles.isEmpty {
            let sample = untrackedFiles.prefix(5).joined(separator: ", ")
            let rest = untrackedFiles.count > 5 ? ", and \(untrackedFiles.count - 5) more" : ""
            losses.append("\(Self.count(untrackedFiles.count, "untracked file")): \(sample)\(rest)")
        }
        if deletingBranch, unpushedCommits > 0, !isBranchMerged, !isPullRequestMerged {
            losses.append(
                "\(Self.count(unpushedCommits, "commit")) that "
                + "\(unpushedCommits == 1 ? "exists" : "exist") on no other branch, tag or remote"
            )
        }
        if detachedCommits > 0 {
            losses.append(
                "\(Self.count(detachedCommits, "commit")) made on a detached HEAD, "
                + "held by no branch"
            )
        }
        return losses
    }

    /// The half worth mentioning rather than warning about: ignored paths that differ from the
    /// main checkout.
    ///
    /// Still said out loud, because `git worktree remove` really does delete them and nothing
    /// else in the app would tell anyone. Never called a loss, because git was never holding a
    /// copy to lose: these are files a `.gitignore` deliberately keeps out of every commit.
    /// `ReproduciblePaths` has already dropped everything a package manager could put back, which
    /// is what makes naming the rest worth the reader's time.
    public var ignoredFileNotes: [String] {
        guard !modifiedIgnoredFiles.isEmpty else { return [] }

        let sample = modifiedIgnoredFiles.prefix(5).joined(separator: ", ")
        let rest = modifiedIgnoredFiles.count > 5
            ? ", and \(modifiedIgnoredFiles.count - 5) more"
            : ""
        // A trailing slash means the entry is a whole directory, named once, so the noun has to
        // allow for one.
        let folders = modifiedIgnoredFiles.contains { $0.hasSuffix("/") }
        let one = modifiedIgnoredFiles.count == 1
        let noun = switch (one, folders) {
        case (true, true): "ignored folder"
        case (true, false): "ignored file"
        case (false, true): "ignored files and folders"
        case (false, false): "ignored files"
        }
        return [
            "\(modifiedIgnoredFiles.count) \(noun) that \(one ? "differs" : "differ") "
            + "from the main checkout: \(sample)\(rest)"
        ]
    }

    /// "1 untracked file", "3 untracked files". The list this feeds is read at the moment somebody
    /// decides whether to destroy their work, which is the worst place in the app for the reader to
    /// have to translate "file(s)" for themselves.
    private static func count(_ value: Int, _ noun: String) -> String {
        "\(value) \(noun)\(value == 1 ? "" : "s")"
    }
}

/// Everything throwing a workspace away would destroy, gathered before anything is thrown.
///
/// This is the expensive half of `Git`: it walks every ref in the repository and byte-compares
/// the ignored files a worktree is carrying, which is why nothing polls it and why the cheap
/// question a pull request strip asks is `LocalWork` in `Git+Diffs.swift` instead. It is all
/// computed up front because removing a worktree and deleting its branch leaves nothing to
/// recover from afterwards.
extension Git {
    /// Everything archiving this workspace would destroy, gathered before anything is removed.
    ///
    /// `unpushedCommits` deliberately means "reachable from this branch and from no other ref",
    /// not "ahead of the base branch". A commit that also lives on a remote, on a tag or on
    /// another branch survives deleting this one, and refusing to archive over it would be
    /// noise. A commit nothing else points at does not survive.
    public static func safetyReport(
        worktree: String,
        branch: String,
        base: String,
        repo: String
    ) async throws -> WorkspaceSafetyReport {
        try validate(branch: branch)

        var report = WorkspaceSafetyReport()

        // A directory that is not there holds nothing, so an empty report is the true answer. A
        // directory that IS there and cannot be read as a repository is a different thing
        // entirely: git could not be asked, and every field below would be a zero standing in for
        // an answer nobody has. `isSafeToDiscard` would read that as "nothing at stake" and let
        // the worktree be deleted, so it throws instead, and the caller shows the reason.
        if FileManager.default.fileExists(atPath: worktree) {
            guard await isRepository(worktree) else {
                throw ShellError(
                    command: "git status",
                    status: 128,
                    stderr: "\(worktree) is not a git worktree, so what is in it cannot be checked"
                )
            }
            let status = try await checkRaw(["status", "--porcelain", "-z"], in: worktree)
            (report.hasUncommittedChanges, report.untrackedFiles) = parseStatus(status.stdout)
            report.modifiedIgnoredFiles = try await divergentIgnoredFiles(worktree: worktree, repo: repo)
            report.detachedCommits = try await detachedCommitCount(worktree: worktree, repo: repo)
        }

        guard await branchExists(branch, in: repo) else { return report }

        let refs = try await check(
            ["for-each-ref", "--format=%(refname)", "refs/heads", "refs/remotes", "refs/tags"],
            in: repo
        ).lines
        // Feeding the other refs in on stdin rather than as arguments, because a repository with
        // thousands of tags would otherwise blow past the argument limit.
        let negated = refs
            .filter { $0 != "refs/heads/\(branch)" }
            .map { "^\($0)" }
            .joined(separator: "\n")
        let unique = try await check(
            ["rev-list", "--count", "--stdin", "refs/heads/\(branch)"],
            in: repo,
            stdin: negated.isEmpty ? "\n" : negated + "\n"
        )
        report.unpushedCommits = Int(unique.trimmed) ?? 0

        if (try? validate(ref: base, label: "base branch")) != nil {
            let merged = try await run(
                ["merge-base", "--is-ancestor", "refs/heads/\(branch)", base], in: repo
            )
            report.isBranchMerged = merged.ok
        }

        return report
    }

    /// `status --porcelain -z` records: `XY path`, and for a rename or copy the new path is
    /// followed by a second record holding the old path.
    static func parseStatus(_ data: Data) -> (dirty: Bool, untracked: [String]) {
        var dirty = false
        var untracked: [String] = []
        var records = nulRecords(data)[...]

        while let record = records.popFirst() {
            guard record.count > 3 else { continue }
            let code = String(decoding: record.prefix(2), as: UTF8.self)
            let path = String(decoding: record.dropFirst(3), as: UTF8.self)
            if code == "??" {
                untracked.append(path)
            } else {
                dirty = true
                if code.contains("R") || code.contains("C") { _ = records.popFirst() }
            }
        }
        return (dirty, untracked)
    }

    /// Ignored paths in the worktree that the main checkout does not have, or has differently,
    /// with everything a tool can rebuild left out. See `ReproduciblePaths`.
    ///
    /// Only ignored paths are considered, because tracked and untracked ones are already covered.
    /// An ignored file that matches the main checkout byte for byte is not a loss: Bloom copied it
    /// there and the original is still where it came from.
    ///
    /// `--directory` is what makes this cheap enough to run in front of a confirmation. It
    /// collapses a wholly ignored directory into one record with a trailing slash, so a
    /// `node_modules` of forty thousand files costs a single line instead of forty thousand
    /// paths and forty thousand file reads. It is also the level the reproducibility rule wants
    /// to work at: the answer for `node_modules/` is the answer for everything inside it.
    static func divergentIgnoredFiles(worktree: String, repo: String) async throws -> [String] {
        let ignored = try await checkRaw(
            ["ls-files", "--others", "--ignored", "--exclude-standard", "--directory", "-z"],
            in: worktree
        )

        var paths: [String] = []
        for record in nulRecords(ignored.stdout) {
            let path = String(decoding: record, as: UTF8.self)
            guard !path.isEmpty, !ReproduciblePaths.canBeRebuilt(path) else { continue }
            paths.append(path)
        }

        // Git lists a directory and, sometimes, a directory nested inside it. Reporting both
        // would name the same loss twice, so only the outermost entry survives: it covers
        // everything the inner one did.
        let directories = paths.filter { $0.hasSuffix("/") }
        let covering = paths.filter { path in
            !directories.contains { $0 != path && path.hasPrefix($0) }
        }

        var divergent: [String] = []
        for path in covering {
            let here = (worktree as NSString).appendingPathComponent(path)
            let there = (repo as NSString).appendingPathComponent(path)
            if path.hasSuffix("/") {
                // Named as one line rather than expanded. "storage/logs/" says what would be
                // lost; its two hundred files say it two hundred times.
                if directoryDiffers(here, there) { divergent.append(path) }
            } else if fileDiffers(here, there) {
                divergent.append(path)
            }
        }
        return divergent.sorted()
    }

    /// Whether two files at the same repository-relative path hold different bytes.
    ///
    /// Size first. Two files of different lengths cannot be equal, and answering from the inode
    /// rather than from the contents is what keeps a directory of large ignored files off the
    /// critical path of a confirmation.
    ///
    /// Every uncertain answer is "differs". A file that exists here and cannot be read is not
    /// evidence that nothing is at stake; it is the absence of evidence, and the version of this
    /// that skipped an unreadable file quietly counted it as safe to destroy. The only case that
    /// returns false without looking is a file that is no longer there at all, which cannot be
    /// destroyed by removing the directory it has already left.
    static func fileDiffers(_ here: String, _ there: String) -> Bool {
        let manager = FileManager.default
        guard manager.fileExists(atPath: here) else { return false }
        // Exists only in the worktree, so removing the worktree is the end of it.
        guard manager.fileExists(atPath: there) else { return true }

        let mySize = (try? manager.attributesOfItem(atPath: here)[.size] as? Int)
        let theirSize = (try? manager.attributesOfItem(atPath: there)[.size] as? Int)
        if let mySize, let theirSize, mySize != theirSize { return true }

        guard let mine = manager.contents(atPath: here) else { return true }
        guard let theirs = manager.contents(atPath: there) else { return true }
        return mine != theirs
    }

    /// Whether a wholly ignored directory holds anything the main checkout does not.
    ///
    /// Bounded on purpose. An unknown ignored directory big enough to make this expensive is
    /// already something whose contents nobody is going to read out of a confirmation, and a
    /// walk that could run for a minute is exactly what this rewrite exists to remove. Past the
    /// bound the answer is "it differs", because the alternative is telling somebody there is
    /// nothing at stake on the strength of a check that gave up.
    static func directoryDiffers(_ here: String, _ there: String, limit: Int = 2_000) -> Bool {
        let manager = FileManager.default
        guard manager.fileExists(atPath: here) else { return false }
        guard manager.fileExists(atPath: there) else { return true }

        guard let walk = manager.enumerator(atPath: here) else { return true }
        var seen = 0
        for case let relative as String in walk {
            var isDirectory: ObjCBool = false
            let file = (here as NSString).appendingPathComponent(relative)
            guard manager.fileExists(atPath: file, isDirectory: &isDirectory), !isDirectory.boolValue
            else { continue }

            seen += 1
            if seen > limit { return true }
            if fileDiffers(file, (there as NSString).appendingPathComponent(relative)) { return true }
        }
        return false
    }

    /// Commits reachable from the worktree's own HEAD and from no ref anywhere.
    ///
    /// Zero unless HEAD is detached, which is what happens when an agent runs `git checkout` in
    /// its worktree. Those commits are held only by the per-worktree reflog, which
    /// `git worktree remove` deletes.
    static func detachedCommitCount(worktree: String, repo: String) async throws -> Int {
        let head = try await run(["symbolic-ref", "--quiet", "HEAD"], in: worktree)
        guard !head.ok else { return 0 }

        let refs = try await check(
            ["for-each-ref", "--format=%(refname)", "refs/heads", "refs/remotes", "refs/tags"],
            in: repo
        ).lines
        let negated = refs.map { "^\($0)" }.joined(separator: "\n")
        let unique = try await run(
            ["rev-list", "--count", "--stdin", "HEAD"],
            in: worktree,
            stdin: negated.isEmpty ? "\n" : negated + "\n"
        )
        guard unique.ok else { return 0 }
        return Int(unique.trimmed) ?? 0
    }
}
