import Foundation
import Testing
@testable import BloomCore

/// Feedback and prompt submissions are the only things Bloom sends that a person composed, so what
/// travels with them is pinned here: the exact keys the endpoint validates, the caps it enforces,
/// and above all the things that must never be in a body no matter what the machine they were sent
/// from is called.
@Suite("Feedback")
struct FeedbackTests {
    private func environment(
        appVersion: String = "0.4.0",
        appBuild: String = "412",
        macOSVersion: String = "26.1.0",
        architecture: Feedback.Architecture = .arm64,
        installSource: Feedback.InstallSource = .release,
        agent: String = "claude",
        agentVersion: String = "2.1.234",
        availableAgents: [String] = ["codex", "claude"],
        permissionMode: String = "accept-edits",
        theme: InstallPing.Theme = .dark,
        displayScale: Double = 2,
        locale: String = "nl-BE"
    ) -> Feedback.Environment {
        Feedback.Environment(
            appVersion: appVersion,
            appBuild: appBuild,
            macOSVersion: macOSVersion,
            architecture: architecture,
            installSource: installSource,
            agent: agent,
            agentVersion: agentVersion,
            availableAgents: availableAgents,
            permissionMode: permissionMode,
            theme: theme,
            displayScale: displayScale,
            locale: locale
        )
    }

    private let token = "3F2504E0-4F89-11D3-9A0C-0305E82C3301"

    private func report(
        message: String = "the sidebar flickers",
        logs: String? = nil,
        images: [Feedback.Image] = [],
        token: String? = "3F2504E0-4F89-11D3-9A0C-0305E82C3301"
    ) -> Feedback.Report {
        Feedback.Report(
            message: message, logs: logs, images: images, token: token, environment: environment()
        )
    }

    private func object(_ value: some Encodable) throws -> [String: Any] {
        let data = try Feedback.json(value)
        return try #require(try JSONSerialization.jsonObject(with: data) as? [String: Any])
    }

    private func text(of body: Feedback.Body) -> String {
        String(decoding: body.data, as: UTF8.self)
    }

    // MARK: - What is in a JSON body

    @Test("a report with no pictures goes as JSON, with four fields")
    func reportKeys() throws {
        let json = try object(report(logs: "10:00:00  archive  nope"))

        #expect(Set(json.keys) == ["message", "logs", "token", "environment"])
    }

    @Test("logs are absent rather than empty when the box was not ticked")
    func reportWithoutLogs() throws {
        let json = try object(report())

        #expect(Set(json.keys) == ["message", "token", "environment"])
    }

    @Test("a token that was not generated by Bloom is left out rather than sent")
    func tokenIsChecked() throws {
        let json = try object(report(token: "/Users/someone/.claude.json"))

        #expect(json["token"] == nil)
    }

    @Test("a prompt submission has prompt, name, token and environment")
    func promptKeys() throws {
        let json = try object(
            Feedback.PromptSubmission(
                prompt: "make the sidebar narrower", name: "Freek", token: token, environment: environment()
            )
        )

        #expect(Set(json.keys) == ["prompt", "name", "token", "environment"])
        #expect(json["name"] as? String == "Freek")
    }

    @Test("an unnamed prompt submission carries no name key at all")
    func promptWithoutName() throws {
        let json = try object(
            Feedback.PromptSubmission(prompt: "make it narrower", name: "   ", token: nil, environment: environment())
        )

        #expect(Set(json.keys) == ["prompt", "environment"])
    }

    @Test("a name the endpoint would refuse is left out rather than sent to be rejected")
    func promptWithARefusableName() throws {
        let json = try object(
            Feedback.PromptSubmission(
                prompt: "make it narrower", name: "someone@example.com", token: nil, environment: environment()
            )
        )

        #expect(json["name"] == nil)
        #expect(json["prompt"] as? String == "make it narrower")
    }

    @Test("a handle keeps its letters and loses its at sign, which is what the endpoint does too")
    func handlesAreNormalised() {
        #expect(Feedback.normalisedName("@freekmurze") == "freekmurze")
        #expect(Feedback.isAcceptableName("@freekmurze"))
        #expect(Feedback.isAcceptableName("Freek Van der Herten"))
        #expect(Feedback.isAcceptableName(""))
        #expect(!Feedback.isAcceptableName("someone@example.com"))
        #expect(!Feedback.isAcceptableName("~/dev/code"))
    }

    // MARK: - The environment block

    @Test("the environment says exactly twelve things and no thirteenth")
    func environmentKeys() throws {
        let json = try object(environment())

        #expect(Set(json.keys) == [
            "app_version",
            "app_build",
            "macos_version",
            "architecture",
            "install_source",
            "agent",
            "agent_version",
            "available_agents",
            "permission_mode",
            "theme",
            "display_scale",
            "locale",
        ])
    }

    @Test("the environment sends the facts as the endpoint expects them")
    func environmentValues() throws {
        let json = try object(environment())

        #expect(json["app_version"] as? String == "0.4.0")
        #expect(json["app_build"] as? String == "412")
        #expect(json["macos_version"] as? String == "26.1.0")
        #expect(json["architecture"] as? String == "arm64")
        #expect(json["install_source"] as? String == "release")
        #expect(json["agent"] as? String == "claude")
        #expect(json["agent_version"] as? String == "2.1.234")
        #expect(json["available_agents"] as? [String] == ["claude", "codex"])
        #expect(json["permission_mode"] as? String == "accept-edits")
        #expect(json["theme"] as? String == "dark")
        #expect(json["display_scale"] as? Double == 2)
        #expect(json["locale"] as? String == "nl-BE")
    }

    @Test("a fact Bloom could not establish is left out, never guessed")
    func unknownFactsAreDropped() throws {
        let json = try object(
            environment(
                appVersion: "", appBuild: "", macOSVersion: "", architecture: .unknown,
                agent: "", agentVersion: "", availableAgents: [], permissionMode: "", locale: ""
            )
        )

        #expect(Set(json.keys) == ["install_source", "theme", "display_scale"])
    }

    @Test("a display scale no screen has is brought inside the range the endpoint takes")
    func displayScaleIsClamped() {
        #expect(environment(displayScale: 0).displayScale == 1)
        #expect(environment(displayScale: 99).displayScale == 4)
    }

    /// The test the whole file exists for. A machine whose every fact is a path, a name or a
    /// credential still produces a body with none of them in it.
    @Test("nothing personal survives into a body, whatever it was handed")
    func nothingPersonalSurvives() throws {
        let hostile = environment(
            appVersion: "0.4.0 (built by someone on someones-macbook)",
            appBuild: "sk-ant-api03-abcdefghijklmnop",
            macOSVersion: "someone@example.com",
            agent: "/opt/homebrew/bin/claude",
            agentVersion: "/Users/someone/.bun/bin/claude 2.1.0",
            availableAgents: ["~/dev/code/secret-project"],
            permissionMode: "Full Access, granted by someone",
            locale: "en_BE (someones-macbook)"
        )

        let body = try String(decoding: Feedback.json(hostile), as: UTF8.self)

        #expect(!body.contains("someone"))
        #expect(!body.contains("/Users"))
        #expect(!body.contains("homebrew"))
        #expect(!body.contains("sk-ant"))
        #expect(!body.contains("secret-project"))
        #expect(!body.contains("@example.com"))
        #expect(!body.contains("macbook"))
        #expect(!body.contains("en_BE"))
    }

    @Test("a log excerpt travels exactly as the excerpt made it")
    func logsAreCarriedVerbatim() throws {
        let excerpt = AppLogExcerpt.excerpt(
            [AppLogExcerpt.Entry(date: Date(), category: "archive", message: "could not archive /Users/someone/dev/x")],
            timeZone: TimeZone(secondsFromGMT: 0)!
        )

        let json = try object(report(logs: excerpt))

        #expect(json["logs"] as? String == excerpt)
        #expect(!excerpt.contains("someone"))
    }

    // MARK: - Pictures, and the multipart body

    private func image(_ name: String = "shot.png", bytes: [UInt8] = [0x89, 0x50]) -> Feedback.Image {
        Feedback.Image(filename: name, contentType: "image/png", data: Data(bytes))
    }

    @Test("a report with pictures goes as multipart, named the way the endpoint reads it")
    func multipartShape() throws {
        let body = try Feedback.body(for: report(images: [image()]), boundary: "TESTBOUNDARY")
        let written = text(of: body)

        #expect(body.contentType == "multipart/form-data; boundary=TESTBOUNDARY")
        #expect(written.contains("name=\"message\""))
        #expect(written.contains("name=\"token\""))
        #expect(written.contains("name=\"attachments[]\"; filename=\"shot.png\""))
        #expect(written.contains("Content-Type: image/png"))
        #expect(written.contains("name=\"environment[app_version]\""))
        #expect(written.contains("name=\"environment[available_agents][]\""))
        #expect(written.hasSuffix("--TESTBOUNDARY--\r\n"))
    }

    @Test("the multipart body carries the same environment fields the JSON body does")
    func multipartAndJSONAgree() throws {
        let written = text(of: try Feedback.body(for: report(images: [image()]), boundary: "B"))
        let json = try object(environment())

        for key in json.keys {
            #expect(written.contains("name=\"environment[\(key)]"))
        }
    }

    @Test("a whole number scale is written as one")
    func scaleIsWrittenPlainly() throws {
        let written = text(of: try Feedback.body(for: report(images: [image()]), boundary: "B"))

        #expect(written.contains("name=\"environment[display_scale]\"\r\n\r\n2\r\n"))
    }

    @Test("a sixth image is not sent")
    func imageCountCap() {
        let images = (0..<8).map { image("shot\($0).png") }

        #expect(report(images: images).images.count == Feedback.maxImages)
    }

    @Test("an image name is a name, never a path, even though the endpoint drops it anyway")
    func imageNamesAreCleaned() {
        let cleaned = Feedback.Image(
            filename: "/Users/someone/Desktop/Screenshot 2026-08-21 at 10.11.12.png",
            contentType: "image/png",
            data: Data()
        )

        #expect(cleaned.filename == "Screenshot 2026-08-21 at 10.11.12.png")
    }

    @Test("a filename cannot break out of the part header it is written into")
    func imageNamesCannotEscape() {
        let cleaned = Feedback.Image(filename: "a\";\r\nX-Evil: 1.png", contentType: "image/png", data: Data())

        #expect(!cleaned.filename.contains("\""))
        #expect(!cleaned.filename.contains("\r"))
        #expect(!cleaned.filename.contains("\n"))
    }

    @Test("an unfamiliar content type is not repeated back")
    func contentTypeIsChecked() {
        #expect(Feedback.Image(filename: "a.png", contentType: "application/pdf", data: Data()).contentType == "image/png")
        #expect(Feedback.Image(filename: "a.webp", contentType: "image/webp", data: Data()).contentType == "image/webp")
    }

    // MARK: - Caps

    @Test("a very long message is cut rather than refused")
    func messageCap() {
        let long = report(message: String(repeating: "a", count: Feedback.maxMessageCharacters + 500))

        #expect(long.message.count == Feedback.maxMessageCharacters)
    }

    @Test("the sheet warns before the limit and says what will be lost past it")
    func remainingCounter() {
        #expect(Feedback.remainingMessage(count: 100, limit: 5_000) == nil)
        #expect(Feedback.remainingMessage(count: 4_900, limit: 5_000) == "100 characters left")
        #expect(Feedback.remainingMessage(count: 5_200, limit: 5_000)?.contains("first 5000") == true)
    }

    @Test("a report with no words in it cannot be sent")
    func emptyMessageCannotSend() {
        #expect(!Feedback.canSend(message: "   \n "))
        #expect(Feedback.canSend(message: "it broke"))
    }

    // MARK: - Where it goes

    @Test("both kinds go to runbloom.app unless a local endpoint is named")
    func endpoints() {
        #expect(Feedback.endpoint(.report, environment: [:])?.absoluteString == Feedback.reportEndpoint)
        #expect(Feedback.endpoint(.prompt, environment: [:])?.absoluteString == Feedback.promptEndpoint)
    }

    @Test("a local endpoint wins, which is the only way this is developed")
    func endpointOverride() {
        let found = Feedback.endpoint(
            .report, environment: ["BLOOM_FEEDBACK_URL": "http://127.0.0.1:8787/api/feedback-submissions"]
        )

        #expect(found?.absoluteString == "http://127.0.0.1:8787/api/feedback-submissions")
    }

    @Test("an override that is not an http URL is refused")
    func endpointOverrideIsChecked() {
        #expect(Feedback.endpoint(.report, environment: ["BLOOM_FEEDBACK_URL": "file:///tmp/out.json"]) == nil)
        #expect(
            Feedback.endpoint(.report, environment: ["BLOOM_FEEDBACK_URL": "   "])?.absoluteString
                == Feedback.reportEndpoint
        )
    }

    @Test("the request says what it is carrying and takes no cookies")
    func requestShape() throws {
        let body = try Feedback.body(for: report())
        let request = Feedback.request(to: URL(string: "https://example.test/x")!, body: body, appVersion: "0.4.0")

        #expect(request.httpMethod == "POST")
        #expect(request.value(forHTTPHeaderField: "Content-Type") == "application/json")
        #expect(request.value(forHTTPHeaderField: "User-Agent") == "Bloom/0.4.0")
        #expect(request.httpShouldHandleCookies == false)
    }

    @Test("a multipart request says its own boundary in the header")
    func multipartRequestHeader() throws {
        let body = try Feedback.body(for: report(images: [image()]), boundary: "XYZ")
        let request = Feedback.request(to: URL(string: "https://example.test/x")!, body: body, appVersion: "0.4.0")

        #expect(request.value(forHTTPHeaderField: "Content-Type") == "multipart/form-data; boundary=XYZ")
    }

    // MARK: - What the answer means

    @Test("what each status code means to somebody watching")
    func outcomes() {
        #expect(Feedback.outcome(statusCode: 201) == .sent)
        #expect(Feedback.outcome(statusCode: 422) == .refused)
        #expect(Feedback.outcome(statusCode: 413) == .refused)
        #expect(Feedback.outcome(statusCode: 429, retryAfter: "120") == .throttled(retryAfter: 120))
        #expect(Feedback.outcome(statusCode: 503) == .unreachable)
        #expect(Feedback.outcome(statusCode: 0) == .unreachable)
    }

    @Test("every failure says the text is still there, and success says nothing")
    func failureMessages() throws {
        #expect(Feedback.failureMessage(.sent) == nil)

        for outcome: Feedback.Outcome in [.refused, .throttled(retryAfter: nil), .unreachable] {
            #expect(Feedback.failureMessage(outcome)?.isEmpty == false)
        }

        #expect(Feedback.failureMessage(.unreachable)?.contains(Feedback.supportEmail) == true)
    }

    // MARK: - What the machine is

    @Test("a build knows whether it is a release or somebody's own")
    func installSources() {
        #expect(Feedback.InstallSource(buildChannel: "release", masterCommit: nil) == .release)
        #expect(Feedback.InstallSource(buildChannel: "release", masterCommit: "abc1234") == .local)
        #expect(Feedback.InstallSource(buildChannel: nil, masterCommit: nil) == .local)
    }

    @Test("a translated process reports the slice it is running as")
    func architectures() {
        #expect(Feedback.Architecture(isARM: true, isTranslated: false).wireName == "arm64")
        #expect(Feedback.Architecture(isARM: false, isTranslated: false).wireName == "x86_64")
        #expect(Feedback.Architecture(isARM: true, isTranslated: true).wireName == "x86_64")
        #expect(Feedback.Architecture.unknown.wireName == nil)
    }

    @Test("every permission mode has a slug the endpoint accepts")
    func permissionModeWireNames() {
        for mode in PermissionMode.allCases {
            #expect(InstallPing.matches(Feedback.wireName(mode), Feedback.slugPattern))
        }
    }

    @Test("every agent slug the ping uses is a slug this endpoint takes too")
    func agentWireNames() {
        for kind in AgentKind.allCases {
            #expect(InstallPing.matches(InstallPing.wireName(kind), Feedback.slugPattern))
        }
    }

    // MARK: - The copy

    @Test("the logs checkbox says what it sends, and the sheet says how to reach a person")
    func copyDescribesWhatIsSent() {
        #expect(Feedback.Copy.logsDetail.contains("half hour"))
        #expect(Feedback.Copy.logsDetail.contains("View"))
        #expect(Feedback.Copy.reportBlurb.contains(Feedback.supportEmail))
        #expect(Feedback.Copy.environmentNote.contains("No file"))
        #expect(Feedback.Copy.promptNamePlaceholder.contains("not an email"))
    }
}
