import Foundation
import Testing
@testable import BloomCore

/// Feedback and prompt submissions are the only things Bloom sends that a person composed, so what
/// travels with them is pinned here: the exact keys the endpoint validates, the caps it enforces,
/// and above all the things that must never be in a body no matter what the machine they were sent
/// from is called.
@Suite("Feedback")
struct FeedbackTests {
    private func environment(
        appVersion: String = "0.4.0",
        appBuild: String = "412",
        macOSVersion: String = "26.1.0",
        architecture: Feedback.Architecture = .arm64,
        translated: Bool? = false,
        installSource: Feedback.InstallSource = .release,
        agent: String = "claude",
        agentVersion: String = "2.1.234",
        availableAgents: [String] = ["codex", "claude"],
        permissionMode: String = "accept-edits",
        theme: InstallPing.Theme = .dark,
        displayScale: Double = 2,
        locale: String = "nl-BE"
    ) -> Feedback.Environment {
        Feedback.Environment(
            appVersion: appVersion,
            appBuild: appBuild,
            macOSVersion: macOSVersion,
            architecture: architecture,
            translated: translated,
            installSource: installSource,
            agent: agent,
            agentVersion: agentVersion,
            availableAgents: availableAgents,
            permissionMode: permissionMode,
            theme: theme,
            displayScale: displayScale,
            locale: locale
        )
    }

    private let token = "3F2504E0-4F89-11D3-9A0C-0305E82C3301"

    private func report(
        message: String = "the sidebar flickers",
        email: String? = nil,
        logs: String? = nil,
        images: [Feedback.Image] = [],
        token: String? = "3F2504E0-4F89-11D3-9A0C-0305E82C3301"
    ) -> Feedback.Report {
        Feedback.Report(
            message: message, email: email, logs: logs, images: images, token: token,
            environment: environment()
        )
    }

    private func object(_ value: some Encodable) throws -> [String: Any] {
        let data = try Feedback.json(value)
        return try #require(try JSONSerialization.jsonObject(with: data) as? [String: Any])
    }

    private func text(of body: Feedback.Body) -> String {
        String(decoding: body.data, as: UTF8.self)
    }

    // MARK: - What is in a JSON body

    @Test("a report with no pictures goes as JSON, with four fields")
    func reportKeys() throws {
        let json = try object(report(logs: "10:00:00  archive  nope"))

        #expect(Set(json.keys) == ["message", "logs", "token", "environment"])
    }

    @Test("logs are absent rather than empty when the box was not ticked")
    func reportWithoutLogs() throws {
        let json = try object(report())

        #expect(Set(json.keys) == ["message", "token", "environment"])
    }

    @Test("a token that was not generated by Bloom is left out rather than sent")
    func tokenIsChecked() throws {
        let json = try object(report(token: "/Users/someone/.claude.json"))

        #expect(json["token"] == nil)
    }

    @Test("a prompt submission has prompt, name, token and environment")
    func promptKeys() throws {
        let json = try object(
            Feedback.PromptSubmission(
                prompt: "make the sidebar narrower", name: "Freek", email: nil, token: token,
                environment: environment()
            )
        )

        #expect(Set(json.keys) == ["prompt", "name", "token", "environment"])
        #expect(json["name"] as? String == "Freek")
    }

    @Test("an unnamed prompt submission carries no name key at all")
    func promptWithoutName() throws {
        let json = try object(
            Feedback.PromptSubmission(
                prompt: "make it narrower", name: "   ", email: nil, token: nil, environment: environment()
            )
        )

        #expect(Set(json.keys) == ["prompt", "environment"])
    }

    @Test("a name the endpoint would refuse is left out rather than sent to be rejected")
    func promptWithARefusableName() throws {
        let json = try object(
            Feedback.PromptSubmission(
                prompt: "make it narrower", name: "someone@example.com", email: nil, token: nil,
                environment: environment()
            )
        )

        #expect(json["name"] == nil)
        #expect(json["prompt"] as? String == "make it narrower")
    }

    @Test("a handle keeps its letters and loses its at sign, which is what the endpoint does too")
    func handlesAreNormalised() {
        #expect(Feedback.normalisedName("@freekmurze") == "freekmurze")
        #expect(Feedback.isAcceptableName("@freekmurze"))
        #expect(Feedback.isAcceptableName("Freek Van der Herten"))
        #expect(Feedback.isAcceptableName(""))
        #expect(!Feedback.isAcceptableName("someone@example.com"))
        #expect(!Feedback.isAcceptableName("~/dev/code"))
    }

    // MARK: - The environment block

    @Test("the environment says exactly thirteen things and no fourteenth")
    func environmentKeys() throws {
        let json = try object(environment())

        #expect(Set(json.keys) == [
            "app_version",
            "app_build",
            "macos_version",
            "architecture",
            "translated",
            "install_source",
            "agent",
            "agent_version",
            "available_agents",
            "permission_mode",
            "theme",
            "display_scale",
            "locale",
        ])
    }

    @Test("the environment sends the facts as the endpoint expects them")
    func environmentValues() throws {
        let json = try object(environment())

        #expect(json["app_version"] as? String == "0.4.0")
        #expect(json["app_build"] as? String == "412")
        #expect(json["macos_version"] as? String == "26.1.0")
        #expect(json["architecture"] as? String == "arm64")
        #expect(json["translated"] as? Bool == false)
        #expect(json["install_source"] as? String == "release")
        #expect(json["agent"] as? String == "claude")
        #expect(json["agent_version"] as? String == "2.1.234")
        #expect(json["available_agents"] as? [String] == ["claude", "codex"])
        #expect(json["permission_mode"] as? String == "accept-edits")
        #expect(json["theme"] as? String == "dark")
        #expect(json["display_scale"] as? Double == 2)
        #expect(json["locale"] as? String == "nl-BE")
    }

    @Test("a fact Bloom could not establish is left out, never guessed")
    func unknownFactsAreDropped() throws {
        let json = try object(
            environment(
                appVersion: "", appBuild: "", macOSVersion: "", architecture: .unknown,
                translated: true,
                agent: "", agentVersion: "", availableAgents: [], permissionMode: "", locale: ""
            )
        )

        #expect(Set(json.keys) == ["install_source", "theme", "display_scale"])
    }

    @Test("a display scale no screen has is brought inside the range the endpoint takes")
    func displayScaleIsClamped() {
        #expect(environment(displayScale: 0).displayScale == 1)
        #expect(environment(displayScale: 99).displayScale == 4)
    }

    /// The test the whole file exists for. A machine whose every fact is a path, a name or a
    /// credential still produces a body with none of them in it.
    @Test("nothing personal survives into a body, whatever it was handed")
    func nothingPersonalSurvives() throws {
        let hostile = environment(
            appVersion: "0.4.0 (built by someone on someones-macbook)",
            appBuild: "sk-ant-api03-abcdefghijklmnop",
            macOSVersion: "someone@example.com",
            agent: "/opt/homebrew/bin/claude",
            agentVersion: "/Users/someone/.bun/bin/claude 2.1.0",
            availableAgents: ["~/dev/code/secret-project"],
            permissionMode: "Full Access, granted by someone",
            locale: "en_BE (someones-macbook)"
        )

        let body = try String(decoding: Feedback.json(hostile), as: UTF8.self)

        #expect(!body.contains("someone"))
        #expect(!body.contains("/Users"))
        #expect(!body.contains("homebrew"))
        #expect(!body.contains("sk-ant"))
        #expect(!body.contains("secret-project"))
        #expect(!body.contains("@example.com"))
        #expect(!body.contains("macbook"))
        #expect(!body.contains("en_BE"))
    }

    @Test("a log excerpt travels exactly as the excerpt made it")
    func logsAreCarriedVerbatim() throws {
        let excerpt = AppLogExcerpt.excerpt(
            [AppLogExcerpt.Entry(date: Date(), category: "archive", message: "could not archive /Users/someone/dev/x")],
            timeZone: TimeZone(secondsFromGMT: 0)!
        )

        let json = try object(report(logs: excerpt))

        #expect(json["logs"] as? String == excerpt)
        #expect(!excerpt.contains("someone"))
    }

    // MARK: - Pictures, and the multipart body

    /// A real PNG signature, because what a picture is is now read from its bytes rather than
    /// from what the caller called it.
    private static let pngBytes = Data([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x01])
    private static let jpegBytes = Data([0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10])

    private func image(_ data: Data = FeedbackTests.pngBytes, declaring type: String = "image/png") -> Feedback.Image {
        Feedback.Image(contentType: type, data: data)
    }

    @Test("a report with pictures goes as multipart, named the way the endpoint reads it")
    func multipartShape() throws {
        let body = try Feedback.body(for: report(images: [image()]), boundary: "TESTBOUNDARY")
        let written = text(of: body)

        #expect(body.contentType == "multipart/form-data; boundary=TESTBOUNDARY")
        #expect(written.contains("name=\"message\""))
        #expect(written.contains("name=\"token\""))
        #expect(written.contains("name=\"attachments[]\"; filename=\"attachment.png\""))
        #expect(written.contains("Content-Type: image/png"))
        #expect(written.contains("name=\"environment[app_version]\""))
        #expect(written.contains("name=\"environment[available_agents][]\""))
        #expect(written.hasSuffix("--TESTBOUNDARY--\r\n"))
    }

    @Test("the multipart body carries the same environment fields the JSON body does")
    func multipartAndJSONAgree() throws {
        let written = text(of: try Feedback.body(for: report(images: [image()]), boundary: "B"))
        let json = try object(environment())

        for key in json.keys {
            #expect(written.contains("name=\"environment[\(key)]"))
        }
    }

    @Test("a whole number scale is written as one")
    func scaleIsWrittenPlainly() throws {
        let written = text(of: try Feedback.body(for: report(images: [image()]), boundary: "B"))

        #expect(written.contains("name=\"environment[display_scale]\"\r\n\r\n2\r\n"))
        // A boolean goes as a digit, which is what a form carries.
        #expect(written.contains("name=\"environment[translated]\"\r\n\r\n0\r\n"))
    }

    @Test("a sixth image is not sent")
    func imageCountCap() {
        let images = (0..<8).map { _ in image() }

        #expect(report(images: images).images.count == Feedback.maxImages)
    }

    @Test("the name that travels is Bloom's, and it matches what the bytes are")
    func imageNamesAreDerived() {
        #expect(image().filename == "attachment.png")
        #expect(image(FeedbackTests.jpegBytes).filename == "attachment.jpg")
    }

    /// The case the endpoint would refuse: a JPEG somebody renamed to `.png`. What the bytes say
    /// has to win, or the extension and the sniffed type disagree and the whole upload is dropped.
    @Test("bytes beat the name they arrived under")
    func bytesDecideTheType() {
        let renamed = image(FeedbackTests.jpegBytes, declaring: "image/png")

        #expect(renamed.contentType == "image/jpeg")
        #expect(renamed.filename == "attachment.jpg")
    }

    @Test("what a run of bytes is, read from the bytes", arguments: [
        (Data([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]), "image/png"),
        (Data([0xFF, 0xD8, 0xFF, 0xE0]), "image/jpeg"),
        (Data("GIF89a....".utf8), "image/gif"),
        (Data("RIFF????WEBPVP8 ".utf8), "image/webp"),
        (Data("????ftypheic".utf8), "image/heic"),
        (Data("????ftypmif1".utf8), "image/heif"),
    ])
    func sniffing(bytes: Data, type: String) {
        #expect(Feedback.sniffedContentType(bytes) == type)
    }

    @Test("something that is not a picture is not recognised as one")
    func sniffingRefusesTheRest() {
        #expect(Feedback.sniffedContentType(Data("%PDF-1.7".utf8)) == nil)
        #expect(Feedback.sniffedContentType(Data("<svg xmlns=".utf8)) == nil)
        #expect(Feedback.sniffedContentType(Data()) == nil)
    }

    @Test("every type Bloom sends has an extension the endpoint's list names")
    func everyTypeHasAnExtension() {
        let accepted = ["jpg", "jpeg", "png", "gif", "webp", "heic", "heif"]

        for type in Feedback.imageContentTypes {
            #expect(accepted.contains(Feedback.fileExtension(for: type)))
        }
    }

    // MARK: - Caps

    @Test("a very long message is cut rather than refused")
    func messageCap() {
        let long = report(message: String(repeating: "a", count: Feedback.maxMessageCharacters + 500))

        #expect(long.message.count == Feedback.maxMessageCharacters)
    }

    @Test("the sheet warns before the limit and says what will be lost past it")
    func remainingCounter() {
        #expect(Feedback.remainingMessage(count: 100, limit: 5_000) == nil)
        #expect(Feedback.remainingMessage(count: 4_900, limit: 5_000) == "100 characters left")
        #expect(Feedback.remainingMessage(count: 5_200, limit: 5_000)?.contains("first 5000") == true)
    }

    @Test("the three limits are the endpoint's, and each is said in its own words")
    func limits() {
        #expect(Feedback.maxImages == 5)
        #expect(Feedback.maxImageBytes == 8 * 1024 * 1024)
        #expect(Feedback.maxTotalImageBytes == 12 * 1024 * 1024)
        // The total has to fit inside what a request may weigh, or the sentence above is a lie
        // and the refusal arrives as a 413 instead.
        #expect(Feedback.maxTotalImageBytes < Feedback.maximumBodyBytes)

        let tooLarge = Feedback.tooLargeMessage(name: "shot.png", bytes: 9 * 1024 * 1024)
        #expect(tooLarge.contains("shot.png"))
        #expect(tooLarge.contains("8 MB"))
        #expect(Feedback.tooManyMessage().contains("5"))
        #expect(Feedback.tooMuchMessage().contains("12 MB"))
        // Three different sentences, so the one on screen says which limit was hit.
        #expect(Set([tooLarge, Feedback.tooManyMessage(), Feedback.tooMuchMessage()]).count == 3)
    }

    @Test("a report with no words in it cannot be sent")
    func emptyMessageCannotSend() {
        #expect(!Feedback.canSend(message: "   \n "))
        #expect(Feedback.canSend(message: "it broke"))
    }

    // MARK: - Where it goes

    @Test("both kinds go to runbloom.app unless a local endpoint is named")
    func endpoints() {
        #expect(Feedback.endpoint(.report, environment: [:])?.absoluteString == Feedback.reportEndpoint)
        #expect(Feedback.endpoint(.prompt, environment: [:])?.absoluteString == Feedback.promptEndpoint)
    }

    @Test("a local endpoint wins, which is the only way this is developed")
    func endpointOverride() {
        let found = Feedback.endpoint(
            .report, environment: ["BLOOM_FEEDBACK_URL": "http://127.0.0.1:8787/api/feedback-submissions"]
        )

        #expect(found?.absoluteString == "http://127.0.0.1:8787/api/feedback-submissions")
    }

    @Test("an override that is not an http URL is refused")
    func endpointOverrideIsChecked() {
        #expect(Feedback.endpoint(.report, environment: ["BLOOM_FEEDBACK_URL": "file:///tmp/out.json"]) == nil)
        #expect(
            Feedback.endpoint(.report, environment: ["BLOOM_FEEDBACK_URL": "   "])?.absoluteString
                == Feedback.reportEndpoint
        )
    }

    @Test("the request says what it is carrying and takes no cookies")
    func requestShape() throws {
        let body = try Feedback.body(for: report())
        let request = Feedback.request(to: URL(string: "https://example.test/x")!, body: body, appVersion: "0.4.0")

        #expect(request.httpMethod == "POST")
        #expect(request.value(forHTTPHeaderField: "Content-Type") == "application/json")
        #expect(request.value(forHTTPHeaderField: "User-Agent") == "Bloom/0.4.0")
        #expect(request.httpShouldHandleCookies == false)
    }

    @Test("a multipart request says its own boundary in the header")
    func multipartRequestHeader() throws {
        let body = try Feedback.body(for: report(images: [image()]), boundary: "XYZ")
        let request = Feedback.request(to: URL(string: "https://example.test/x")!, body: body, appVersion: "0.4.0")

        #expect(request.value(forHTTPHeaderField: "Content-Type") == "multipart/form-data; boundary=XYZ")
    }

    // MARK: - What the answer means

    @Test("what each status code means to somebody watching")
    func outcomes() {
        #expect(Feedback.outcome(statusCode: 201) == .sent)
        #expect(Feedback.outcome(statusCode: 422) == .refused)
        #expect(Feedback.outcome(statusCode: 413) == .refused)
        #expect(Feedback.outcome(statusCode: 429, retryAfter: "120") == .throttled(retryAfter: 120))
        #expect(Feedback.outcome(statusCode: 503) == .unreachable)
        #expect(Feedback.outcome(statusCode: 0) == .unreachable)
    }

    @Test("every failure says the text is still there, and success says nothing")
    func failureMessages() throws {
        #expect(Feedback.failureMessage(.sent) == nil)

        for outcome: Feedback.Outcome in [.refused, .throttled(retryAfter: nil), .unreachable] {
            #expect(Feedback.failureMessage(outcome)?.isEmpty == false)
        }

        #expect(Feedback.failureMessage(.unreachable)?.contains(Feedback.supportEmail) == true)
    }

    // MARK: - What the machine is

    @Test("a build knows whether it is a release, somebody's own, or somebody's own with edits in it")
    func installSources() {
        #expect(Feedback.InstallSource(buildChannel: "release", masterCommit: nil) == .release)
        #expect(Feedback.InstallSource(buildChannel: "release", masterCommit: "abc1234") == .local)
        #expect(Feedback.InstallSource(buildChannel: nil, masterCommit: nil) == .local)

        // Either shape of marker says the working tree had edits in it.
        #expect(Feedback.InstallSource(buildChannel: nil, masterCommit: "abc1234-dirty") == .localDirty)
        #expect(Feedback.InstallSource(buildChannel: nil, masterCommit: nil, isDirty: true) == .localDirty)
        // And a release is a release whatever a stray marker says, because it was built from a tag.
        #expect(Feedback.InstallSource(buildChannel: "release", masterCommit: nil, isDirty: true) == .release)

        for source in Feedback.InstallSource.allCases {
            #expect(InstallPing.matches(source.rawValue, Feedback.slugPattern))
        }
    }

    @Test("a translated process reports the slice it is running as, and says it was translated")
    func architectures() {
        #expect(Feedback.Architecture(isARM: true, isTranslated: false).wireName == "arm64")
        #expect(Feedback.Architecture(isARM: false, isTranslated: false).wireName == "x86_64")
        #expect(Feedback.Architecture(isARM: true, isTranslated: true).wireName == "x86_64")
        #expect(Feedback.Architecture.unknown.wireName == nil)

        // An Intel Mac and Rosetta are the same slice and different bugs, which is the whole
        // reason the second field exists.
        #expect(environment(architecture: .x86_64, translated: false).translated == false)
        #expect(environment(architecture: .x86_64, translated: true).translated == true)
        // Half an answer about the processor is worse than none.
        #expect(environment(architecture: .unknown, translated: true).translated == nil)
    }

    @Test("every permission mode has a slug the endpoint accepts")
    func permissionModeWireNames() {
        for mode in PermissionMode.allCases {
            #expect(InstallPing.matches(Feedback.wireName(mode), Feedback.slugPattern))
        }
    }

    @Test("every agent slug the ping uses is a slug this endpoint takes too")
    func agentWireNames() {
        for kind in AgentKind.allCases {
            #expect(InstallPing.matches(InstallPing.wireName(kind), Feedback.slugPattern))
        }
    }

    // MARK: - The reference

    @Test("the reference in a reply is read back, so it can be shown")
    func readsTheReference() {
        let body = Data(#"{"reference":"01J8ZQ7Z9K3M4N5P6Q7R8S9T0V"}"#.utf8)

        #expect(Feedback.reference(in: body) == "01J8ZQ7Z9K3M4N5P6Q7R8S9T0V")
    }

    /// A server's string is about to be printed into Bloom's own interface, so it is checked
    /// rather than trusted: anything that is not shaped like a reference is not one.
    @Test("a reply that is not a reference is not shown as one", arguments: [
        #"{"reference":"see your email"}"#,
        #"{"reference":""}"#,
        #"{"reference":"<script>alert(1)</script>"}"#,
        #"{"ok":true}"#,
        "not json at all",
    ])
    func refusesAStrangeReference(body: String) {
        #expect(Feedback.reference(in: Data(body.utf8)) == nil)
    }

    /// The reference is still parsed, because the endpoint still returns one and a malformed reply
    /// still must not be believed. It is simply no longer read out to anybody: the card that
    /// replaces the form says thank you and nothing else. See `Feedback.Copy.reportSentDetail`.
    @Test("the thank you says nothing about a reference")
    func thanksIsPlain() {
        #expect(!Feedback.Copy.reportSent.contains("Reference"))
        #expect(!Feedback.Copy.reportSentDetail.contains("Reference"))
        #expect(!Feedback.Copy.promptSentDetail.contains("Reference"))
    }

    // MARK: - The copy

    @Test("the logs checkbox says what it sends, and the sheet says how to reach a person")
    func copyDescribesWhatIsSent() {
        #expect(Feedback.Copy.logsDetail.contains("half hour"))
        #expect(Feedback.Copy.logsDetail.contains("credential"))
        #expect(Feedback.Copy.logsDetail.contains("branch names"))
        #expect(Feedback.Copy.reportBlurb.contains(Feedback.supportEmail))
        #expect(Feedback.Copy.environmentNote.contains("No file"))
        #expect(Feedback.Copy.promptNamePlaceholder.contains("not an email"))
    }
}

/// The optional address both sheets grew, which is the only piece of contact information anything
/// in Bloom sends. Every case here is a way somebody could leave the field in a state the endpoint
/// would refuse, and the rule throughout is the same: drop the address, keep the words.
@Suite("Feedback: the address")
struct FeedbackEmailTests {
    private func environment() -> Feedback.Environment {
        Feedback.Environment(
            appVersion: "0.3.0",
            appBuild: "452",
            macOSVersion: "26.0",
            architecture: .arm64,
            translated: false,
            installSource: Feedback.InstallSource(buildChannel: "release", masterCommit: nil, isDirty: nil),
            agent: "claude_code",
            agentVersion: "1.0.0",
            availableAgents: ["claude"],
            permissionMode: "accept-edits",
            theme: .dark,
            displayScale: 2,
            locale: "nl-BE"
        )
    }

    private func object(_ value: some Encodable) throws -> [String: Any] {
        let data = try Feedback.json(value)
        return try #require(try JSONSerialization.jsonObject(with: data) as? [String: Any])
    }

    private func report(email: String?) -> Feedback.Report {
        Feedback.Report(
            message: "the sidebar flickers", email: email, logs: nil, images: [], token: nil,
            environment: environment()
        )
    }

    private func submission(email: String?) -> Feedback.PromptSubmission {
        Feedback.PromptSubmission(
            prompt: "make it narrower", name: nil, email: email, token: nil, environment: environment()
        )
    }

    @Test("a report carries the address it was given")
    func reportCarriesTheAddress() throws {
        #expect(try object(report(email: "freek@spatie.be"))["email"] as? String == "freek@spatie.be")
    }

    @Test("a prompt submission carries it too")
    func promptCarriesTheAddress() throws {
        #expect(try object(submission(email: "freek@spatie.be"))["email"] as? String == "freek@spatie.be")
    }

    @Test("no address means no key at all, rather than a key holding an empty string")
    func absentIsAbsent() throws {
        #expect(try object(report(email: nil))["email"] == nil)
        #expect(try object(report(email: "   "))["email"] == nil)
        #expect(try object(submission(email: nil))["email"] == nil)
    }

    /// The sheet has already said what is wrong with it, and losing an address is better than
    /// losing the report it was attached to.
    @Test("an address the endpoint would refuse is left out rather than sent to be rejected")
    func refusableAddressIsDropped() throws {
        let json = try object(report(email: "not an address"))

        #expect(json["email"] == nil)
        #expect(json["message"] as? String == "the sidebar flickers")
    }

    @Test("surrounding whitespace goes, and the case of the local part does not")
    func normalising() {
        #expect(Feedback.normalisedEmail("  Freek@Spatie.be  ") == "Freek@Spatie.be")
        #expect(Feedback.normalisedEmail(String(repeating: "a", count: 300)).count == 254)
    }

    @Test("an empty field is acceptable, because hearing back is opted into rather than required")
    func emptyIsAcceptable() {
        #expect(Feedback.isAcceptableEmail(""))
        #expect(Feedback.isAcceptableEmail("   "))
    }

    @Test("what the sheet accepts and what it warns about")
    func acceptance() {
        #expect(Feedback.isAcceptableEmail("freek@spatie.be"))
        #expect(Feedback.isAcceptableEmail("freek+bloom@spatie.co.uk"))
        #expect(Feedback.isAcceptableEmail("a@b.c"))

        #expect(!Feedback.isAcceptableEmail("freek"))
        #expect(!Feedback.isAcceptableEmail("freek@spatie"))
        #expect(!Feedback.isAcceptableEmail("freek @spatie.be"))
        #expect(!Feedback.isAcceptableEmail("freek@@spatie.be"))
        #expect(!Feedback.isAcceptableEmail("@spatie.be"))
    }

    /// The credit line is the field that gets published, so it still refuses an address however
    /// many other fields now accept one.
    @Test("the name field still refuses an address, and now says where to put it")
    func theNameFieldStillRefusesOne() {
        #expect(!Feedback.isAcceptableName("freek@spatie.be"))
        #expect(Feedback.nameProblem.contains("field of its own"))
    }

    // MARK: - When the sheets may say any of that

    /// The bug this section exists for: `freek@spatie.` marked wrong by the person who had typed
    /// exactly half of it. Nothing is a problem until a send has been attempted, however wrong
    /// the fields would be.
    @Test("a half-typed field is unfinished, not wrong, until Send is pressed")
    func nothingIsWrongBeforeASendIsAttempted() {
        let problems = Feedback.sheetProblems(
            name: "freek@spatie.be", email: "freek@spatie.", afterSendAttempt: false
        )
        #expect(problems.isEmpty)
        #expect(problems.firstField == nil)
    }

    @Test("after a send is attempted, each field says what is wrong with it")
    func problemsAfterAnAttempt() {
        let problems = Feedback.sheetProblems(
            name: "freek@spatie.be", email: "freek@spatie.", afterSendAttempt: true
        )
        #expect(problems.name == Feedback.nameProblem)
        #expect(problems.email == Feedback.emailProblem)
        #expect(problems.message(for: .name) == Feedback.nameProblem)
        #expect(problems.message(for: .email) == Feedback.emailProblem)
    }

    /// Both fields are optional, and this is the case most likely to regress: an empty optional
    /// field marked wrong turns "you may leave this" into a lie.
    @Test("empty optional fields are never a problem, even on the way out")
    func emptyIsNeverAProblem() {
        let problems = Feedback.sheetProblems(name: "", email: "", afterSendAttempt: true)
        #expect(problems.isEmpty)

        let padded = Feedback.sheetProblems(name: "  ", email: "   ", afterSendAttempt: true)
        #expect(padded.isEmpty)
    }

    @Test("a corrected field stops being a problem the moment it is corrected")
    func correctionClears() {
        let problems = Feedback.sheetProblems(
            name: "Freek", email: "freek@spatie.be", afterSendAttempt: true
        )
        #expect(problems.isEmpty)
    }

    /// Focus after a blocked send goes to the first refused field in the sheet's own order, name
    /// above email, which is why the order is pinned here.
    @Test("the first refused field is the one focus should land in")
    func focusOrder() {
        let both = Feedback.sheetProblems(
            name: "freek@spatie.be", email: "nope", afterSendAttempt: true
        )
        #expect(both.firstField == .name)

        let emailOnly = Feedback.sheetProblems(
            name: "Freek", email: "nope", afterSendAttempt: true
        )
        #expect(emailOnly.firstField == .email)
    }

    /// The feedback sheet has no name field and passes nil, which must never read as a problem.
    @Test("a sheet without a name field can only be refused over its address")
    func sheetWithoutANameField() {
        let problems = Feedback.sheetProblems(email: "nope", afterSendAttempt: true)
        #expect(problems.name == nil)
        #expect(problems.firstField == .email)
    }

    // MARK: - The logs checkbox's memory

    @Test("the logs checkbox starts ticked, and an untick is remembered over the default")
    func logsCheckboxMemory() throws {
        let suite = "be.spatie.bloom.tests.\(UUID().uuidString)"
        let defaults = try #require(UserDefaults(suiteName: suite))
        defer { defaults.removePersistentDomain(forName: suite) }

        #expect(Feedback.includesLogs(defaults) == Feedback.includesLogsByDefault)
        #expect(Feedback.includesLogsByDefault)

        Feedback.rememberIncludesLogs(false, in: defaults)
        #expect(!Feedback.includesLogs(defaults))

        Feedback.rememberIncludesLogs(true, in: defaults)
        #expect(Feedback.includesLogs(defaults))
    }
}
